### ISSUE TITLE
[Bug] - Magnet does not accept Accessories Charm slot even with Curios compat mod

### ISSUE THREAD

**Issue by ToxinZangoose** [SuperMartijn642/SimpleMagnets#60]
**Version Info**
- Minecraft, 1.21
- Simple Magnets, 1.1.11+a

**Description of the Bug**
When opening accessories, the magnet does not allow itself to be added to the charm slot.

**Steps to Reproduce**
Magnet Charm Slot:
1. Launch Minecraft on latest NeoForge: (21.0.163)
2. Craft magnet and attempt to place in curio/accessory slot
3. Notice that the slot for the charm does not accept the magnet or vice versa

**Screenshots**
N/A

**Comment by ToxinZangoose** [comment]
Tested again, the keybind does work.

**Comment by SuperMartijn642** [comment]
Ah seems I manually created the tags for Curios and since 1.21 changed the path from `tags/items/...` to `tags/item/...` it no longer loads the tags.
I added the tags to datagen now, so they automatically get generated and changes like these should fix themselves.

It should be fixed now in version 1.1.11a/b of Simple Magnets.
That being said, I don't even see a Curios version for 1.21 though, so I have no way of testing it 🤔
